name: Run all tests for Moodle 40+

on: [push, pull_request]

jobs:
  workflow_group_40_plus_ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/group-40-plus-ci.yml@main
    with:
      disable_phpunit: true
