#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
name: Releasing in the Plugins directory

on:
  push:
    branches:
      - MOODLE_400_STABLE
    paths:
      - 'version.php'

jobs:
  workflow_group_40_plus_release:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/group-40-plus-release.yml@main
    with:
      plugin_name: mod_reengagement
      disable_phpunit: true
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
